// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsKKIdMZjS4-7fxzrUMIgkRekrLZYTbFY',
    appId: '1:69294984603:web:56f344481f3273a7e5653e',
    messagingSenderId: '69294984603',
    projectId: 'leadunity-68950',
    authDomain: 'leadunity-68950.firebaseapp.com',
    storageBucket: 'leadunity-68950.firebasestorage.app',
    measurementId: 'G-9QK0F1YVM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALEvk-R9Vyjaj6Nq1V8oc0MHBECq4xUHw',
    appId: '1:69294984603:android:183e0c87fca0c1ede5653e',
    messagingSenderId: '69294984603',
    projectId: 'leadunity-68950',
    storageBucket: 'leadunity-68950.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs0tYXUjcVKq9HzlpF4lHQEDKNXTAVFi4',
    appId: '1:69294984603:ios:a239425a55821a25e5653e',
    messagingSenderId: '69294984603',
    projectId: 'leadunity-68950',
    storageBucket: 'leadunity-68950.firebasestorage.app',
    iosBundleId: 'com.example.leadunity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs0tYXUjcVKq9HzlpF4lHQEDKNXTAVFi4',
    appId: '1:69294984603:ios:5bd6ae65bd9aa545e5653e',
    messagingSenderId: '69294984603',
    projectId: 'leadunity-68950',
    storageBucket: 'leadunity-68950.firebasestorage.app',
    iosBundleId: 'com.example.linkUnity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsKKIdMZjS4-7fxzrUMIgkRekrLZYTbFY',
    appId: '1:69294984603:web:6fa49face7f42b0fe5653e',
    messagingSenderId: '69294984603',
    projectId: 'leadunity-68950',
    authDomain: 'leadunity-68950.firebaseapp.com',
    storageBucket: 'leadunity-68950.firebasestorage.app',
    measurementId: 'G-S0VLMNS8PG',
  );
}
