// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSAEG2ssr0OAADGmcxW28Dy4jM2ze0ybA',
    appId: '1:630087844154:web:21dee5afb473304d28d003',
    messagingSenderId: '630087844154',
    projectId: 'leadunity-a4757',
    authDomain: 'leadunity-a4757.firebaseapp.com',
    storageBucket: 'leadunity-a4757.firebasestorage.app',
    measurementId: 'G-N75S58RCGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADaQAFIXmqdjDZd-R4xBn3mmCEj1ycvm0',
    appId: '1:630087844154:android:3b17cf6f09a42fc228d003',
    messagingSenderId: '630087844154',
    projectId: 'leadunity-a4757',
    storageBucket: 'leadunity-a4757.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiO2i-whYot91H61CYfcKCIgOkCiGo5-c',
    appId: '1:630087844154:ios:0c187e80127c4d1328d003',
    messagingSenderId: '630087844154',
    projectId: 'leadunity-a4757',
    storageBucket: 'leadunity-a4757.firebasestorage.app',
    iosBundleId: 'com.example.linkUnity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiO2i-whYot91H61CYfcKCIgOkCiGo5-c',
    appId: '1:630087844154:ios:0c187e80127c4d1328d003',
    messagingSenderId: '630087844154',
    projectId: 'leadunity-a4757',
    storageBucket: 'leadunity-a4757.firebasestorage.app',
    iosBundleId: 'com.example.linkUnity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSAEG2ssr0OAADGmcxW28Dy4jM2ze0ybA',
    appId: '1:630087844154:web:5cb449a1d94a5f6728d003',
    messagingSenderId: '630087844154',
    projectId: 'leadunity-a4757',
    authDomain: 'leadunity-a4757.firebaseapp.com',
    storageBucket: 'leadunity-a4757.firebasestorage.app',
    measurementId: 'G-L9Q0C66BVC',
  );
}
